import { createServerFn } from '@tanstack/react-start'
import { z } from 'zod'
import * as React from 'react'
import { render } from '@react-email/components'
import { supabaseAdmin } from '@/integrations/supabase/client.server'
import { TEMPLATES } from '@/lib/email-templates/registry'

const SITE_NAME = 'bizzsurfergo'
const SENDER_DOMAIN = 'notify.bizzsurfer.com'
const FROM_DOMAIN = 'notify.bizzsurfer.com'
const PUBLIC_SITE = 'https://go.bizzsurfer.ai'

const ListingApplicationSchema = z.object({
  name: z.string().trim().min(1).max(200),
  email: z.string().trim().email().max(320),
  company: z.string().trim().max(200).optional().nullable(),
  offeringType: z.enum(['Agent', 'Service', 'Playbook', 'Template', 'Other']),
  title: z.string().trim().min(1).max(200),
  description: z.string().trim().min(10).max(5000),
  website: z.string().trim().max(500).optional().nullable(),
  // Anti-spam controls (server-validated, never trust client)
  honeypot: z.string().max(0).optional().default(''),
  elapsedMs: z.number().int().min(0).max(86_400_000).optional().default(0),
  userAgent: z.string().max(1024).optional().nullable(),
})

async function enqueueTemplate(opts: {
  templateName: string
  recipient: string
  data: Record<string, any>
  replyTo?: string
}) {
  const tmpl = TEMPLATES[opts.templateName]
  if (!tmpl) throw new Error(`Template not found: ${opts.templateName}`)
  const recipient = tmpl.to || opts.recipient
  const messageId = crypto.randomUUID()

  const element = React.createElement(tmpl.component, opts.data)
  const html = await render(element)
  const text = await render(element, { plainText: true })
  const subject = typeof tmpl.subject === 'function' ? tmpl.subject(opts.data) : tmpl.subject

  await supabaseAdmin.from('email_send_log').insert({
    message_id: messageId,
    template_name: opts.templateName,
    recipient_email: recipient,
    status: 'pending',
  })

  const payload: Record<string, any> = {
    message_id: messageId,
    to: recipient,
    from: `${SITE_NAME} <noreply@${FROM_DOMAIN}>`,
    sender_domain: SENDER_DOMAIN,
    subject,
    html,
    text,
    purpose: 'transactional',
    label: opts.templateName,
    idempotency_key: messageId,
    queued_at: new Date().toISOString(),
  }
  if (opts.replyTo) payload.reply_to = opts.replyTo

  const { error } = await supabaseAdmin.rpc('enqueue_email', {
    queue_name: 'transactional_emails',
    payload,
  })

  if (error) {
    await supabaseAdmin.from('email_send_log').insert({
      message_id: messageId,
      template_name: opts.templateName,
      recipient_email: recipient,
      status: 'failed',
      error_message: error.message,
    })
  }
}

export const submitListingApplication = createServerFn({ method: 'POST' })
  .inputValidator((data) => ListingApplicationSchema.parse(data))
  .handler(async ({ data }) => {
    // Anti-spam: honeypot field must be empty + min 2s on form (bots auto-fill instantly)
    if (data.honeypot && data.honeypot.length > 0) {
      // Silently accept to avoid leaking the trap
      return { success: true as const, token: null }
    }
    if (data.elapsedMs > 0 && data.elapsedMs < 2000) {
      return { success: true as const, token: null }
    }

    // Insert application row — token is generated by DB default
    const { data: inserted, error: insertError } = await supabaseAdmin
      .from('marketplace_listing_applications')
      .insert({
        name: data.name,
        email: data.email,
        company: data.company || null,
        offering_type: data.offeringType,
        title: data.title,
        description: data.description,
        website: data.website || null,
        user_agent: data.userAgent || null,
        source: 'marketplace_apply_dialog',
      })
      .select('id, public_token')
      .single()

    if (insertError || !inserted) {
      console.error('Listing application insert failed', insertError)
      throw new Error('Failed to submit application')
    }

    const statusUrl = `${PUBLIC_SITE}/marketplace/application/${inserted.public_token}`

    await Promise.allSettled([
      enqueueTemplate({
        templateName: 'marketplace-listing-application',
        recipient: 'info@bizzsurfer.com',
        data: {
          name: data.name,
          email: data.email,
          company: data.company,
          offeringType: data.offeringType,
          title: data.title,
          description: data.description,
          website: data.website,
        },
        replyTo: data.email,
      }),
      enqueueTemplate({
        templateName: 'marketplace-listing-confirmation',
        recipient: data.email,
        data: {
          name: data.name,
          title: data.title,
          offeringType: data.offeringType,
          statusUrl,
        },
      }),
    ])

    return { success: true as const, token: inserted.public_token as string }
  })
