import { createServerFn } from "@tanstack/react-start";
import { z } from "zod";
import { requireSupabaseAuth } from "@/integrations/supabase/auth-middleware";
import { supabaseAdmin } from "@/integrations/supabase/client.server";

/**
 * Joins the caller to a team. Requires an owner-controlled cryptographic
 * `invite_token` (UUID) that was generated by the owner when they invited
 * this email — there is no longer a way to silently join a team just by
 * knowing the owner's user UUID.
 */
export const requestTeamJoin = createServerFn({ method: "POST" })
  .middleware([requireSupabaseAuth])
  .inputValidator((d) =>
    z
      .object({
        owner_id: z.string().uuid(),
        invite_token: z.string().uuid(),
      })
      .parse(d),
  )
  .handler(async ({ data, context }) => {
    const { userId, claims } = context;
    const email = ((claims as { email?: string }).email ?? "").toLowerCase();
    if (!email) throw new Error("Your account has no email on file.");
    if (data.owner_id === userId) {
      throw new Error("You can't join your own team.");
    }

    // The invite_token must match an existing team_members row the owner
    // explicitly created for this owner_id. This prevents anyone who just
    // knows another user's UUID from force-joining their team.
    const { data: invite, error: inviteErr } = await supabaseAdmin
      .from("team_members")
      .select("id, email, status")
      .eq("owner_id", data.owner_id)
      .eq("invite_token", data.invite_token)
      .maybeSingle();
    if (inviteErr) throw new Error(inviteErr.message);
    if (!invite) {
      throw new Error("This team link is no longer valid.");
    }
    if (invite.email && invite.email.toLowerCase() !== email) {
      throw new Error("This invite was issued to a different email address.");
    }

    const { data: row, error } = await supabaseAdmin
      .from("team_members")
      .update({
        email,
        name:
          (claims as { user_metadata?: { full_name?: string } }).user_metadata?.full_name ?? null,
        status: "active",
        accepted_at: new Date().toISOString(),
      })
      .eq("id", invite.id)
      .select("id")
      .single();
    if (error) throw new Error(error.message);
    return { ok: true, id: row.id as string };
  });
