/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PodcastRouteImport } from './routes/podcast'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FeedDotxmlRouteImport } from './routes/feed[.]xml'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as AtomDotxmlRouteImport } from './routes/atom[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InsightsIndexRouteImport } from './routes/insights.index'
import { Route as MarketplaceCheckoutRouteImport } from './routes/marketplace.checkout'
import { Route as MarketplaceListingIdRouteImport } from './routes/marketplace.$listingId'
import { Route as JoinTeamOwnerIdRouteImport } from './routes/join-team.$ownerId'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as InsightsSlugRouteImport } from './routes/insights.$slug'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as AdminStorageRouteImport } from './routes/admin.storage'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminInsightsCommentsRouteImport } from './routes/admin.insights-comments'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicHooksIframeAlertCheckRouteImport } from './routes/api/public/hooks/iframe-alert-check'
import { Route as ApiPublicEventsEventIdDoticsRouteImport } from './routes/api/public/events/$eventId[.]ics'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PodcastRoute = PodcastRouteImport.update({
  id: '/podcast',
  path: '/podcast',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedDotxmlRoute = FeedDotxmlRouteImport.update({
  id: '/feed.xml',
  path: '/feed.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomDotxmlRoute = AtomDotxmlRouteImport.update({
  id: '/atom.xml',
  path: '/atom.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsIndexRoute = InsightsIndexRouteImport.update({
  id: '/insights/',
  path: '/insights/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceCheckoutRoute = MarketplaceCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => MarketplaceRoute,
} as any)
const MarketplaceListingIdRoute = MarketplaceListingIdRouteImport.update({
  id: '/$listingId',
  path: '/$listingId',
  getParentRoute: () => MarketplaceRoute,
} as any)
const JoinTeamOwnerIdRoute = JoinTeamOwnerIdRouteImport.update({
  id: '/join-team/$ownerId',
  path: '/join-team/$ownerId',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsSlugRoute = InsightsSlugRouteImport.update({
  id: '/insights/$slug',
  path: '/insights/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminStorageRoute = AdminStorageRouteImport.update({
  id: '/admin/storage',
  path: '/admin/storage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/admin/seo',
  path: '/admin/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInsightsCommentsRoute = AdminInsightsCommentsRouteImport.update({
  id: '/admin/insights-comments',
  path: '/admin/insights-comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/admin/alerts',
  path: '/admin/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIframeAlertCheckRoute =
  ApiPublicHooksIframeAlertCheckRouteImport.update({
    id: '/api/public/hooks/iframe-alert-check',
    path: '/api/public/hooks/iframe-alert-check',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEventsEventIdDoticsRoute =
  ApiPublicEventsEventIdDoticsRouteImport.update({
    id: '/api/public/events/$eventId.ics',
    path: '/api/public/events/$eventId.ics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/chat': typeof ChatRoute
  '/events': typeof EventsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/insights-comments': typeof AdminInsightsCommentsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/storage': typeof AdminStorageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join-team/$ownerId': typeof JoinTeamOwnerIdRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/events/$eventId.ics': typeof ApiPublicEventsEventIdDoticsRoute
  '/api/public/hooks/iframe-alert-check': typeof ApiPublicHooksIframeAlertCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/chat': typeof ChatRoute
  '/events': typeof EventsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/insights-comments': typeof AdminInsightsCommentsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/storage': typeof AdminStorageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join-team/$ownerId': typeof JoinTeamOwnerIdRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/insights': typeof InsightsIndexRoute
  '/api/public/events/$eventId.ics': typeof ApiPublicEventsEventIdDoticsRoute
  '/api/public/hooks/iframe-alert-check': typeof ApiPublicHooksIframeAlertCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atom.xml': typeof AtomDotxmlRoute
  '/chat': typeof ChatRoute
  '/events': typeof EventsRoute
  '/feed.xml': typeof FeedDotxmlRoute
  '/login': typeof LoginRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/podcast': typeof PodcastRoute
  '/pricing': typeof PricingRoute
  '/profile': typeof ProfileRoute
  '/reset-password': typeof ResetPasswordRoute
  '/resources': typeof ResourcesRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/insights-comments': typeof AdminInsightsCommentsRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/storage': typeof AdminStorageRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/insights/$slug': typeof InsightsSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/join-team/$ownerId': typeof JoinTeamOwnerIdRoute
  '/marketplace/$listingId': typeof MarketplaceListingIdRoute
  '/marketplace/checkout': typeof MarketplaceCheckoutRoute
  '/insights/': typeof InsightsIndexRoute
  '/api/public/events/$eventId.ics': typeof ApiPublicEventsEventIdDoticsRoute
  '/api/public/hooks/iframe-alert-check': typeof ApiPublicHooksIframeAlertCheckRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atom.xml'
    | '/chat'
    | '/events'
    | '/feed.xml'
    | '/login'
    | '/marketplace'
    | '/podcast'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/insights-comments'
    | '/admin/seo'
    | '/admin/storage'
    | '/checkout/return'
    | '/insights/$slug'
    | '/invite/$token'
    | '/join-team/$ownerId'
    | '/marketplace/$listingId'
    | '/marketplace/checkout'
    | '/insights/'
    | '/api/public/events/$eventId.ics'
    | '/api/public/hooks/iframe-alert-check'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atom.xml'
    | '/chat'
    | '/events'
    | '/feed.xml'
    | '/login'
    | '/marketplace'
    | '/podcast'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/insights-comments'
    | '/admin/seo'
    | '/admin/storage'
    | '/checkout/return'
    | '/insights/$slug'
    | '/invite/$token'
    | '/join-team/$ownerId'
    | '/marketplace/$listingId'
    | '/marketplace/checkout'
    | '/insights'
    | '/api/public/events/$eventId.ics'
    | '/api/public/hooks/iframe-alert-check'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/atom.xml'
    | '/chat'
    | '/events'
    | '/feed.xml'
    | '/login'
    | '/marketplace'
    | '/podcast'
    | '/pricing'
    | '/profile'
    | '/reset-password'
    | '/resources'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/alerts'
    | '/admin/analytics'
    | '/admin/insights-comments'
    | '/admin/seo'
    | '/admin/storage'
    | '/checkout/return'
    | '/insights/$slug'
    | '/invite/$token'
    | '/join-team/$ownerId'
    | '/marketplace/$listingId'
    | '/marketplace/checkout'
    | '/insights/'
    | '/api/public/events/$eventId.ics'
    | '/api/public/hooks/iframe-alert-check'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtomDotxmlRoute: typeof AtomDotxmlRoute
  ChatRoute: typeof ChatRoute
  EventsRoute: typeof EventsRoute
  FeedDotxmlRoute: typeof FeedDotxmlRoute
  LoginRoute: typeof LoginRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  PodcastRoute: typeof PodcastRoute
  PricingRoute: typeof PricingRoute
  ProfileRoute: typeof ProfileRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResourcesRoute: typeof ResourcesRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminInsightsCommentsRoute: typeof AdminInsightsCommentsRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminStorageRoute: typeof AdminStorageRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  InsightsSlugRoute: typeof InsightsSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  JoinTeamOwnerIdRoute: typeof JoinTeamOwnerIdRoute
  InsightsIndexRoute: typeof InsightsIndexRoute
  ApiPublicEventsEventIdDoticsRoute: typeof ApiPublicEventsEventIdDoticsRoute
  ApiPublicHooksIframeAlertCheckRoute: typeof ApiPublicHooksIframeAlertCheckRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/podcast': {
      id: '/podcast'
      path: '/podcast'
      fullPath: '/podcast'
      preLoaderRoute: typeof PodcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feed.xml': {
      id: '/feed.xml'
      path: '/feed.xml'
      fullPath: '/feed.xml'
      preLoaderRoute: typeof FeedDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atom.xml': {
      id: '/atom.xml'
      path: '/atom.xml'
      fullPath: '/atom.xml'
      preLoaderRoute: typeof AtomDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/': {
      id: '/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof InsightsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/checkout': {
      id: '/marketplace/checkout'
      path: '/checkout'
      fullPath: '/marketplace/checkout'
      preLoaderRoute: typeof MarketplaceCheckoutRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/marketplace/$listingId': {
      id: '/marketplace/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/$listingId'
      preLoaderRoute: typeof MarketplaceListingIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
    '/join-team/$ownerId': {
      id: '/join-team/$ownerId'
      path: '/join-team/$ownerId'
      fullPath: '/join-team/$ownerId'
      preLoaderRoute: typeof JoinTeamOwnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/$slug': {
      id: '/insights/$slug'
      path: '/insights/$slug'
      fullPath: '/insights/$slug'
      preLoaderRoute: typeof InsightsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/storage': {
      id: '/admin/storage'
      path: '/admin/storage'
      fullPath: '/admin/storage'
      preLoaderRoute: typeof AdminStorageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/admin/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/insights-comments': {
      id: '/admin/insights-comments'
      path: '/admin/insights-comments'
      fullPath: '/admin/insights-comments'
      preLoaderRoute: typeof AdminInsightsCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/admin/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/iframe-alert-check': {
      id: '/api/public/hooks/iframe-alert-check'
      path: '/api/public/hooks/iframe-alert-check'
      fullPath: '/api/public/hooks/iframe-alert-check'
      preLoaderRoute: typeof ApiPublicHooksIframeAlertCheckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/$eventId.ics': {
      id: '/api/public/events/$eventId.ics'
      path: '/api/public/events/$eventId.ics'
      fullPath: '/api/public/events/$eventId.ics'
      preLoaderRoute: typeof ApiPublicEventsEventIdDoticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceListingIdRoute: typeof MarketplaceListingIdRoute
  MarketplaceCheckoutRoute: typeof MarketplaceCheckoutRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceListingIdRoute: MarketplaceListingIdRoute,
  MarketplaceCheckoutRoute: MarketplaceCheckoutRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtomDotxmlRoute: AtomDotxmlRoute,
  ChatRoute: ChatRoute,
  EventsRoute: EventsRoute,
  FeedDotxmlRoute: FeedDotxmlRoute,
  LoginRoute: LoginRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  PodcastRoute: PodcastRoute,
  PricingRoute: PricingRoute,
  ProfileRoute: ProfileRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResourcesRoute: ResourcesRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminAlertsRoute: AdminAlertsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminInsightsCommentsRoute: AdminInsightsCommentsRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminStorageRoute: AdminStorageRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  InsightsSlugRoute: InsightsSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  JoinTeamOwnerIdRoute: JoinTeamOwnerIdRoute,
  InsightsIndexRoute: InsightsIndexRoute,
  ApiPublicEventsEventIdDoticsRoute: ApiPublicEventsEventIdDoticsRoute,
  ApiPublicHooksIframeAlertCheckRoute: ApiPublicHooksIframeAlertCheckRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
